pipelines:
  configurations:
    arrayImputation:
      1:
        cromwellSubmissionPollingIntervalInSeconds: 600
        inputKeysToPrependWithStorageWorkspaceContainerUrl: [ "refDict", "referencePanelPathPrefix", "geneticMapsPath" ]
        storageWorkspaceContainerUrl: ${env.pipelines.imputation.storageWorkspaceContainerUrl}
        inputsWithCustomValues:
          referencePanelPathPrefix: ${env.pipelines.imputation.referencePanelPathPrefixCustomValue}
        useCallCaching: true
        deleteIntermediateFiles: false
        memoryRetryMultiplier: 2.0
