pipelines:
  configurations:
    pipelines:
      arrayImputation:
        1:
          cromwellSubmissionPollingIntervalInSeconds: 600
          inputKeysToPrependWithStorageWorkspaceContainerUrl: [ "refDict", "referencePanelPathPrefix", "geneticMapsPath" ]
          storageWorkspaceContainerUrl: ${env.pipelines.imputation.storageWorkspaceContainerUrl}
          inputsWithCustomValues:
            referencePanelPathPrefix: ${env.pipelines.imputation.referencePanelPathPrefixCustomValue}
          useCallCaching: true
          deleteIntermediateFiles: false
          memoryRetryMultiplier: 2.0
        2:
          cromwellSubmissionPollingIntervalInSeconds: 100
          inputKeysToPrependWithStorageWorkspaceContainerUrl: [ "referencePanelPathPrefix", "geneticMapsPath" ]
          storageWorkspaceContainerUrl: ${env.pipelines.imputation.storageWorkspaceContainerUrl}
          inputsWithCustomValues:
            referencePanelPathPrefix: ${env.pipelines.imputation.referencePanelPathPrefixCustomValue}
          useCallCaching: false
          deleteIntermediateFiles: false
          memoryRetryMultiplier: 1.4
      otherPipeline:
        1:
          differentField: "value"
          otherFlag: true
