pipelines:
  configurations:
    common:
      userDataTtlDays: 14
      quotaConsumedPollingIntervalSeconds: 60
      quotaConsumedUseCallCaching: true
      inputQcPollingIntervalSeconds: 60
      inputQcUseCallCaching: true
      monitoringScriptPath: "gs://warp-testing-public/cromwell_monitoring_script2.sh"
    arrayImputation:
      1:
        cromwellSubmissionPollingIntervalInSeconds: 600
        inputKeysToPrependWithStorageWorkspaceContainerUrl: [ "refDict", "referencePanelPathPrefix", "geneticMapsPath" ]
        storageWorkspaceContainerUrl: ${env.pipelines.imputation.storageWorkspaceContainerUrl}
        inputsWithCustomValues:
          referencePanelPathPrefix: ${env.pipelines.imputation.referencePanelPathPrefixCustomValue}
        useCallCaching: true
        deleteIntermediateFiles: false
        memoryRetryMultiplier: 2.0
